### ISSUE TITLE
Click transcript "card" to seek in video

### ISSUE THREAD

**Issue by nairiboo** [hypothesis/via#1051]
Users should be able to click a transcript "card" (chunk of text) to seek the video. Currently only able to do via the timestamp

**Comment by robertknight** [comment]
To add some context from a call where we discussed this: You can click on a timestamp, or anywhere in the timestamp's "column" in the transcript to seek the video, but we don't seek when clicking on the text.

This was an intentional choice on my part to avoid seeking the video when the user is just trying to select some text in order to create an annotation. However it does have the disadvantage of making it harder to find the seeking functionality, and I wasn't sure whether it would be a significant usability problem or not.

One middle-ground option we could implement would be to see the video when clicking on a segment without making a selection, but avoiding seeking the video if you click, drag and release the mouse (or pointer) such that there is a non-empty selection when the mouse is released. I'm not sure whether "long press to select" on mobile will generate a click event, if it does then we might just have to accept that pressing a transcript segment will always seek there on mobile.
