### ISSUE TITLE
YouTube mobile links are still blocked by Checkmate

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#1053]
We recently made it so that YouTube links can be "visited" through Via (in the QA environment at least). These "redirect" to our video player. However the mobile versions of these links that start with `m.youtube.com` instead of `www.youtube.com` are still blocked:

http://qa-via.hypothes.is/https://www.youtube.com/watch?v=CjrmuHHEAes works
http://qa-via.hypothes.is/https://m.youtube.com/watch?v=CjrmuHHEAes is blocked

The mobile links are what you get if you visit YouTube's web app on a phone or tablet and copy the URL.

The expected result is that all the YouTube URL variants that we understand can be visited the same way. I haven't checked all the other YouTube URL variants yet.

**Comment by seanh** [comment]
This is happening because [`get_video_id()`](https://github.com/hypothesis/via/blob/a828bab0d841de78ce309350e562f4c9ffce6369/via/services/youtube.py#L24-L52) doesn't support `m.youtube.com` URLs, so they aren't recognised as YouTube URLs.

Incidentally when looking at this code I noticed that [`parsed.netloc in "youtu.be"`](https://github.com/hypothesis/via/blob/a828bab0d841de78ce309350e562f4c9ffce6369/via/services/youtube.py#L30) is totally wrong but happens to pass the tests.
