### ISSUE TITLE
Increase text size of transcript search field to prevent zoom on iOS

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via#1061]
The transcript search field has a font size < 16px, which causes iOS to zoom into it when focused. We have a solution for this in the client for the annotation edit field. I guess we'll want to do something similar here, or add a more general solution?

In testing this, I noticed that the search bar at the top of the client's UI has the same issue.

**Comment by lyzadanger** [comment]
Immediate fix: on the `Input` component in question, set `touch:text-[16px]`[^1] in `classes`.

More systematic fix: move the `touch-base` font size from the [`client` tailwind config](https://github.com/hypothesis/client/blob/ac31ca43e0d574d1a02147b3c0ba37ca74ee33f9/tailwind.config.mjs#L87-L90) to the upstream `frontend-shared` one so that you can use `touch:text-touch-base` in other projects than the `client` (such as this one). I can help with this if you want to assign the task to me. But the immediate fix above should get you cooking for now.

With shared components I've been taking a minimalist approach and allowing them to inherit wherever possible (versus, e.g., setting a touch-device font size on the shared `Input` itself).

Best solution: Stop using tiny font sizes in our apps :).

[^1]: The `touch:` (media query) variant comes from the [upstream tailwind preset](https://github.com/hypothesis/frontend-shared/blob/b028ea0041ac06e726e571012483431c6d5cd077/src/tailwind.preset.js#L91) in `frontend-shared`.

**Comment by robertknight** [comment]
I looked into where the font size is coming from.

- The Tailwind present sets `font-size: 100%` for `input` elements (and other input controls)
- The video player entry point [applies `text-sm`](https://github.com/hypothesis/via/blob/a89f260c8aa908dd6ef9a8f9c3bca6f4dbab35e8/via/static/styles/video_player.css#L9) to the `body`, which is 14px

The `touch-base` style in the client has [a comment](https://github.com/hypothesis/client/blob/ac31ca43e0d574d1a02147b3c0ba37ca74ee33f9/tailwind.config.mjs#L87-L90) that says:

> Used for touch interfaces in certain UIs

This doesn't explain why it is used. The iOS issue is important context that we need to capture wherever the solution for this ends up.

**Comment by lyzadanger** [comment]
> I looked into where the font size is coming from.

Sorry, did my comment not cover that clearly enough?

Are you asking me to take an action here? Happy to do so, it's just unclear if it's a direct ask.

**Comment by robertknight** [comment]
Hi @lyzadanger - Your comment covered possible fixes, mine was just me making notes about how the current state works. I've been thinking about how to avoid this mistake in future. I think we need a couple of things:

1. Text inputs should have a large-enough font size by default, on touch devices, that this doesn't happen
2. The team needs general awareness of the issue, to reduce the chances they try to override the default and re-introduce the problem

https://github.com/hypothesis/via/pull/1096 implements a possible solution at the level of Tailwind's base layer, and close to where the body font size is defined that is the current effective value. This could work in the client as well, if we made any overrides (eg. for the search input field on desktop) specific to non-touch devices. Thoughts?

> Best solution: Stop using tiny font sizes in our apps :).

Another possibility along these lines would just be to increase the body font size to 16px on touch devices. On desktop that looks too large to my eyes. On mobile, that looks more workable. There would however be extra work to make sure everything lines up with a font size that is different than the current default.

_Edit_: Oh, and we'd have to change the client's font size too, to avoid an incongruity. Changing just the defaults for text inputs will be an easier initial step.
