### ISSUE TITLE
Via: Page with embedded youtube video displays Activity Page in lieu of the video

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/via#193]
https://hypothesis.zendesk.com/agent/tickets/6487

The user built his own assignment in Moodle, but I was able to replicate in Canvas, Bb, Moodle, D2L, and Sakai using https://web.hypothes.is/help/how-to-ocr-optimize-pdfs/. 

To replicate, build an assignment in any of the above LMSs and use our OCR KB article. The embedded youtube video is replaced by the Activity Page with user: set to the account that I
I'm logged into in the browser (i.e., not related to the LMS account).

Console errors from user:
![image](https://user-images.githubusercontent.com/22603275/66683201-dfe88680-ec44-11e9-8491-ce5c3af59610.png)

Similar console errors when I replicated:
![image](https://user-images.githubusercontent.com/22603275/66683290-1aeaba00-ec45-11e9-93d2-890cc1d7a81a.png)

**Comment by klemay** [comment]
Ok, I asked Hannah to take a look at this, and here is what we've learned:

- This does not happen in Via2 and will not be an issue for LMS users once we replace Via-for-HTML-pages in the LMS app. 
- This is happening in Via because we have a bunch of blacklisted urls in Cloudflare that redirect to hypothes.is. The Cloudflare rules were initially set up as a bandaid-fix when Youtube urls were bringing down our Via service
- We could fix this bug for Via by adjusting those regular expressions in Cloudflare-aka not touching any code. 
- Alternatively, moving the blacklist from Cloudflare into the Via repo is quick and do-able. The videos won't work, but instead of showing activity pages, the frames will show an error message that says "This video isn't available" 
- For Via2, rather than playing whack-a-mole and blocking URLs, we should block by content _type_, i.e., all mp4, mp3, & other streaming types. 

Possible ways forward:

Option A
- Adjust redirect rules in Cloudflare for Via - rather than redirecting to hypothes.is (and therefore showing activity pages), we do something less confusing for users
- Create separate issue for blocking by content type in Via2

Option B
- Leave this alone for Via; create separate issue for blocking by content type in Via2

**Comment by ajpeddakotla** [comment]
I'd argue for option A here. And I like the proposal of blocking by content type rather than blocking by URLs (although we should still likely have that option in case we need it).

**Comment by klemay** [comment]
@ajpeddakotla I agree - I'll write up an issue for blocking-by-content-type for Via2 and add a note to the top of this issue.

**Comment by klemay** [comment]
Ok this problem will be solved by 2 Github issues: 

https://github.com/hypothesis/via/issues/194
https://github.com/hypothesis/product-backlog/issues/1080

...so I am closing this issue in favor of those.
