### ISSUE TITLE
Confusing experience when proxied page contains embedded YouTube video

### ISSUE THREAD

**Issue by klemay** [hypothesis/via#194]
Presently, our Via block list redirects content from Youtube and other popular streaming sites and redirects to hypothes.is. That creates a confusing experience if you're annotating a page that contains an embedded video. For instance, see our KB article:

https://via.hypothes.is/https://web.hypothes.is/help/how-to-ocr-optimize-pdfs/

If logged in to Hypothesis, you'll see your activity page embedded in the middle of the page. (If you're not logged in, it will try and fail to load web.hypothes.is in the frame). 

Let's change the behavior so that rather than redirecting to hypothes.is, something more sensible happens. I'll leave it to the engineers to decide what that "sensible something" is, but argue for keeping it as simple as possible.

**Comment by robertknight** [comment]
The reason this was happening is that we had a bunch of page rules set up in Cloudflare which redirected certain proxied URLs to https://hypothes.is, instead of letting Via handle blocking the URL itself. When Via handles a blocked page directly, it presents an HTML page that makes more sense to the user:

<img width="853" alt="Screenshot 2019-11-29 15 35 36" src="https://user-images.githubusercontent.com/2458/69879085-7983fa00-12be-11ea-8628-12c087b5df8d.png">

I have removed all of the Cloudflare rules for the moment, which partly resolves the problem and maybe in a way that is good enough for the moment, since there is a link to the original video in the page.

When we build the new proxy service, I would suggest that we try simply not proxying iframes at all and see if that turns out to be viable.

**Comment by robertknight** [comment]
For reference, Via's own blocklist is here: https://github.com/hypothesis/via/blob/1218392a3d98f5c635751cdd8058db9ceee8e9dd/via/blocker.py#L11
