### ISSUE TITLE
Are we supposed to be being indexed?

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/via#22]
https://www.google.com/search?q=huffington+site%3Avia.hypothes.is

Maybe `robots.txt` is wrong?
https://via.hypothes.is/robots.txt

**Comment by tilgovi** [comment]
That's from January, so maybe Google just doesn't purge it?

**Comment by tilgovi** [comment]
Pending purge request filed with Google. If you see new URLs being indexed, let me know, but we used to see Googlebot in our nginx logs and these days we don't. It's pretty easy to notice because it aggressively crawls and via would otherwise let it crawl the whole web so when it used to happen we would experience downtime :).
