### ISSUE TITLE
Add appropriate monitoring and alerting for Via HTML

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#246]
We should decide and implement whatever monitoring and logging we would expect for the Via HTML component.

This should:

 * Match the alerting and monitoring capability of existing Via
 * Ideally provide hints about getting the right sizes for deployment (how many instances we might need etc)

Tasks:

 * [x] Add to Papertrail with groups
 * [x] Add metrics to New Relic (review pending)
 * [x] Add basic alerting on metrics in New Relic
 * [x] Add pingdom coverage (or something similar)

**Comment by indigobravo** [comment]
Due to be working on this the week starting: 2020-09-07

**Comment by indigobravo** [comment]
Deployment work has basically been completed. However, there are some updates that need to be made to the application before we can confirm the correct monitoring is in place. Until that work is complete this ticket is blocked.

**Comment by jon-betts** [comment]
Looks like we are missing newrelic agent

**Comment by indigobravo** [comment]
I have started to put together the  [ViaHTML - Operational Dashboard](https://one.newrelic.com/launcher/dashboards.launcher?pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmRhc2hib2FyZCIsImVudGl0eUlkIjoiTVRNNE5USTRNM3hXU1ZwOFJFRlRTRUpQUVZKRWZHUmhPamMxTnpjMCIsImFjY291bnRJZCI6MTM4NTI4MywiZGFzaGJvYXJkRG9tYWluSWQiOiJkYTo3NTc3NCIsImRhc2hib2FyZE5hbWUiOiJWaWFIVE1MIE9wZXJhdGlvbmFsIERhc2hib2FyZCIsImVkaXRNb2RlIjpmYWxzZSwic2VsZWN0ZWRQYWdlIjoiTVRNNE5USTRNM3hXU1ZwOFJFRlRTRUpQUVZKRWZERTBPRGMzTmpNIiwidXNlRGVmYXVsdFRpbWVSYW5nZSI6ZmFsc2UsImlzVGVtcGxhdGVFbXB0eSI6ZmFsc2UsImlzU2F2aW5nRWRpdENoYW5nZXMiOmZhbHNlfQ==&platform[accountId]=1385283&platform[$isFallbackTimeRange]=false). As it stands we only have the infrastructure agent reporting, so that means we aren't capturing application statics.

We have infra monitoring for:
* High CPU
* High Load Average
* High Memory Consumption
* High Disk Usage

**Comment by indigobravo** [comment]
Further work has been done here and also tested.

Elastic Beanstalk autoscaling has been configured based on CPU usage. These settings will need tweaking as we go live. As it stands they are set to:

* Scale-out / increased node count when CPU AVG goes above `60%` for `4` minutes.
* Scale-In / decrease node count when CPU AVG drops below `30%`.

We have a NewRelic [ViaHTML Status - Scripted](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJzeW50aGV0aWNzLW5lcmRsZXRzLm1vbml0b3Itb3ZlcnZpZXciLCJpc092ZXJ2aWV3Ijp0cnVlLCJyZWZlcnJlcnMiOnsibGF1bmNoZXJJZCI6InN5bnRoZXRpY3MtbmVyZGxldHMuaG9tZSIsIm5lcmRsZXRJZCI6InN5bnRoZXRpY3MtbmVyZGxldHMubW9uaXRvci1saXN0In0sImVudGl0eUlkIjoiTVRNNE5USTRNM3hUV1U1VVNIeE5UMDVKVkU5U2ZEVTJaRGczWXpZM0xXRXpZVEF0TkdaalppMDROV1l5TFROaFpURTRNR1ptWkdFMllnIiwiTG9jYXRpb25TdGF0dXNDaGFydENvbnRhaW5lciI6dHJ1ZX0=&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVE00TlRJNE0zeFRXVTVVU0h4TlQwNUpWRTlTZkRVMlpEZzNZelkzTFdFellUQXROR1pqWmkwNE5XWXlMVE5oWlRFNE1HWm1aR0UyWWciLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoic3ludGhldGljcy1uZXJkbGV0cy5tb25pdG9yLW92ZXJ2aWV3IiwiaXNPdmVydmlldyI6dHJ1ZX19&platform[accountId]=1385283&platform[timeRange][duration]=1800000&platform[$isFallbackTimeRange]=true) check that checks the `/_status` endpoint and sends notifications to Slack if it is not available.

We are using all of our Pingdom checks. So I can not configure anymore without either deleting an existing, or upgrading our account. I feel the NewRelic check provides the same function.

**Comment by jon-betts** [comment]
Sean has given this a look over and thinks it's ok

**Comment by indigobravo** [comment]
ViaHTML incidents raised in NewRelic will now trigger a PagerDuty notification.
