### ISSUE TITLE
jats4r.org throws JS errors in Chrome via Via

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/via#41]
Using Via there are JS errors in Chrome, but it works in Firefox.
http://via.hypothes.is/jats4r.org

![screen shot 2015-09-10 at 9 24 08 am](https://cloud.githubusercontent.com/assets/43209/9792038/2807d1f0-57ac-11e5-945c-c09f7461543f.png)

It also works in Chrome when using the extension.

**Comment by ikreymer** [comment]
It will work if there is a trailing slash: http://via.hypothes.is/jats4r.org/

Looks like the issue is that it attempts to compute the baseURI by doing:

```
document.createElement("a")
a.href = "."
return a.href
```

which correctly returns "http://jats4r.org/" when there is a trailing slash, but ends up with
"http://" if the trailing slash is missing.. I'll see if there's a way to address this for all cases where there's no trailing slash after the host name.

**Comment by tilgovi** [comment]
What is computing the baseURI here? Hypothesis? Or via?

**Comment by ikreymer** [comment]
From hypothes.min.js

```        
     module.exports = function baseURL(doc, href) {
            if ("string" === typeof doc) {
                href = doc;
                doc = null 
            }
            if (null  == doc)
                doc = document;
            if (null  == href)
                href = ".";
            var a = doc.createElement("a");
            a.href = href;
            return a.href
        }
```

**Comment by tilgovi** [comment]
<sigh> that's not a particularly smart polyfill and it's only there to support IE. Let's see what I can do about a better one.

**Comment by tilgovi** [comment]
I just deployed https://github.com/hypothesis/h/commit/0dee222385abcbc2138803ca120427ef0a8409f9 and this is fixed.

**Comment by Klortho** [comment]
Yes, it's working for me, now. Awesome response, guys!
