### ISSUE TITLE
"Time for a coffee break"

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#43]
Follow this URL:
https://via.hypothes.is/https://www.edsurge.com/news/2015-08-30-three-techniques-for-teaching-digital-literacy

And you'll see a placeholder that says "Time for a coffee break" instead of the page.  I seem to remember this from before, so pardon if its a dupe.

**Comment by ikreymer** [comment]
Yes, it's a dupe of https://github.com/hypothesis/via/issues/20

Very odd, since it works on my test app and in webrecorder.. 
https://pywb-h.herokuapp.com/https://www.edsurge.com/news/2015-08-30-three-techniques-for-teaching-digital-literacy

I looked at headers that were being added by via such as `Via: ..squid..` and `Cache-Control: max-age=0` and it works when I add them manually..

Perhaps some sort of IP related thing..

**Comment by dwhly** [comment]
Ack. Sorry for the dupe. Same site too.  So bizarre.
