### ISSUE TITLE
via fails (in safari) for http://45.55.72.107/welcome-to-internet-law/the-basics/chapter-1-introduction-to-law-and-legal-systems/what-is-law/

### ISSUE THREAD

**Issue by judell** [hypothesis/via#44]
![image](https://cloud.githubusercontent.com/assets/46509/9884908/3bcc5334-5b97-11e5-89d1-ef5b19486d58.png)

![image](https://cloud.githubusercontent.com/assets/46509/9884960/7e4a00a8-5b97-11e5-9036-b57bee7ecefc.png)

**Comment by ikreymer** [comment]
Worked for me in Safari 6 with latest, so may be fixed
http://pywb-h.herokuapp.com/http://45.55.72.107/welcome-to-internet-law/the-basics/chapter-1-introduction-to-law-and-legal-systems/what-is-law/

**Comment by nickstenning** [comment]
Definitely still broken in Safari 9 with master (6fbf02631ca326d67dd1e887f9191e78ccf89952).

**Comment by robertknight** [comment]
The symptoms here look very similar to #59 - I think this is essentially the same issue.

@ikreymer - Did you actually mean to say "Safari 6" or is that a typo in the version number? Safari 6 is ancient.

**Comment by ikreymer** [comment]
I don't really use Safari, so that's what I had :) I mostly tested on Chrome and FF, and seems like we need to test Safari as well, and probably IE and Edge..

Need to disable some of the overrides and/or have them gracefully fail if not available..
There are some options already for disabling some of the overrides already through a config setting in config.yaml, though I think not being used at the moment..
