### ISSUE TITLE
via fooled by forbes.com redirection

### ISSUE THREAD

**Issue by judell** [hypothesis/via#50]
From a support email:

"I'd like to share a via link to articles on Forbes, eg :
https://via.hypothes.is/http://www.forbes.com/sites/jamestaylor/2015/09/15/alaska-is-the-front-line-in-global-warming-debate/2/. Clicking that link does not show the article/annotations (I tested Firefox, Chrome, Safari). It seems related to the advertisement and redirection that happens as one reaches any page on Forbes."

I concur with your analysis. I am able to annotate that article using the extension but via seems confused  by the redirection.

**Comment by ikreymer** [comment]
Hmm, in the latest pywb (0.10.9-dev) it is possible to click through the ad, though there may be another issue.

**Comment by dwhly** [comment]
Which are we on?

**Comment by ikreymer** [comment]
The last release, 0.10.8 -- 0.10.9-dev hasn't been released yet.

The amount of ad crap/js on that site is staggering...

**Comment by ikreymer** [comment]
Managed to take a static snapshot (intentionally not using ad-blocker):

https://beta.webrecorder.io/ilya/articles/http://www.forbes.com/sites/jamestaylor/2015/09/15/alaska-is-the-front-line-in-global-warming-debate/2/

**Comment by ikreymer** [comment]
And can then to do this:
https://via.hypothes.is/https://beta.webrecorder.io/ilya/articles/id_/http://www.forbes.com/sites/jamestaylor/2015/09/15/alaska-is-the-front-line-in-global-warming-debate/2/

which appears to work (no annotations so far but looks like its loading from correct source?)

**Comment by dwhly** [comment]
Do you think this is something that the newer version would fix, or is this a difference in deployed environment with via vs webrecorder?

**Comment by judell** [comment]
Indeed. Arguably we should optionally be an ad-blocker :-(

**Comment by ikreymer** [comment]
> Do you think this is something that the newer version would fix, or is this a difference in deployed environment with via vs webrecorder?

That example is actually via rewriting a static "snapshot", archived static HTML with all images removed.. Initially I had to go through all the redirect and close ads to get there.

> Indeed. Arguably we should optionally be an ad-blocker :-(

Since pywb/via is rewriting everything, it certainly would be possible to "block" ads the way an ad blocker does, but not sure if I'm ready to open that can of worms yet :)

**Comment by dwhly** [comment]
> Since pywb/via is rewriting everything, it certainly would be possible to "block" ads the way an ad blocker does, but not sure if I'm ready to open that can of worms yet :)

Nor are we because the last thing we want to be seen as doing is getting in the way of publisher's revenues!

So, earlier you said: 

> in the latest pywb (0.10.9-dev) it is possible to click through the ad, though there may be another issue.

My understanding is that this meant you would see the ad and be able to click through it, just like on the real page.  Is that still a possibility?

**Comment by emvincent** [comment]
Could we annotate that static page on webrecorder.io and later attach all our annotations to the original page as well (like a multiple target url for annotations)? 
This approach could save us time while we find a solution for via to work on the original page. It would also be very useful in many other situations where ads are too annoying and scientists don't even want to annotate as their browser crash for instance.

**Comment by ikreymer** [comment]
There are several issues happening here:

1) The page redirects to a forbes add which requires a click-through to get to actual page. There seems to be no way to avoid that, as its based on presumably some cookies.

2) When clicking-through after ad in via, there is an error that causes the page not to render even in 0.10.9. To make things even more complicated, this only happens when in 'root collection' mode, eg. `via.hypothes.is/<url>`. 
For example,  `via.hypothes.is/<prefix>/<url>` the click-through does work and the page loads with via working. I have not yet been able to find the cause of this...

Now, even if 2) is fixed to work with root collection here, there is still the issue of 1), the ad loading first, so anyone viewing the page live gets redirected to the ad, must click through, wait for page to load and all the ads.

In this case, I think taking a snapshot in webrecorder may be the best option, since it avoids the ad loading and can load pretty fast (loading just static html even), and also avoids 2) (since it never loads from webrecorder.io/<prefix>/<url>)

This is definitely a use case that I'd like to support anyway.  I'm preparing to open-source webrecorder so that you can run your own instance of it, if you'd like. I haven't yet had a chance to think it all through, but perhaps we can chat more separately about how this may all work..

**Comment by ikreymer** [comment]
Ah, finally, have a solution for 2)...
http://pywb-h.herokuapp.com/http://www.forbes.com/sites/jamestaylor/2015/09/15/alaska-is-the-front-line-in-global-warming-debate/2/

Getting ready to release pywb 0.10.9 which will now have this fix..

**Comment by nickstenning** [comment]
Seems fixed.

**Comment by emvincent** [comment]
Thanks for the work on this issue. Although we can now click through the ad to Forbes webpage, we often get stuck in an infinite loop of ads. Sometimes clicking once or twice finally shows the page but often the welcome page reloads each time.
see for instance: https://via.hypothes.is/http://www.forbes.com/sites/jamestaylor/2015/02/09/top-10-global-warming-lies-that-may-shock-you/
Not sure if that can be fixed as well...

**Comment by nikhil-vibhani** [comment]
I have one of the issues in pywb as hypothesis using But in my case pywb taking a long time to load other websites

like http://mydomain.com/https://google/com

It is taking more time to load that stuff, is there any solution.
the hypothesis also faster than my stuff.

Can anyone help me?

Thanks in advance
