### ISSUE TITLE
NY Times... prompting for log in.... but can't log in thru via.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#61]
Not sure there's anything to be done about this.  But seeing that the NY Times seems to now be forcing all via pages to authenticate, which isn't possible to do through via.  Any thoughts on how that might be addressed?

**Comment by robertknight** [comment]
Logging in to any website through Via is a really bad idea from a security point of view in any case and any website that implements login properly shouldn't work with Via - since the credentials would be coming from the wrong domain.

The alternative options I can see boil down to two paths, which can both be pursued:

1) Make the experience of installing the extension, in the context of following a link to see the annotated version of a page, as seamless as possible and available in as many browsers as possible.

2) Render the page elsewhere (ie. not in the browser of the user following a Via link) and deliver only the rendered content (as HTML markup) of the article to the browser. "Elsewhere" could mean in a browser run in a container on a server, captured when the annotations are created etc.

**Comment by nickstenning** [comment]
I'm going to close this. If anything, being able to log in through Via would be a bug, not a feature.
