### ISSUE TITLE
JHU Muse HTTPS issue

### ISSUE THREAD

**Issue by dwhly** [hypothesis/via#8]
https://via.hypothes.is/https://muse.jhu.edu/login?auth=0&type=summary&url=/journals/american_quarterly/v058/58.3dinerstein.html

This returns a pywb error.  

cc @jeremydean

**Comment by tilgovi** [comment]
What error? When? Where? It seems fine to me at a glance.

**Comment by dwhly** [comment]
Sorry.  Pasted the http version.  It's the https version that has the error.
https://via.hypothes.is/https://muse.jhu.edu/login?auth=0&type=summary&url=/journals/american_quarterly/v058/58.3dinerstein.html

**Comment by ikreymer** [comment]
I think this is a python SNI issue: http://bugs.python.org/msg214171
 (though I thought it has been fixed in 2.7.9). I tested it on a clean virtualenv and it worked after  `pip install ndg-httpsclient` which also pulls in the other dependencies mentioned.
So, I think we just need to ndg-httpsclient to requirements.txt

**Comment by nickstenning** [comment]
Yep, this appears to be SNI related. q.v. https://via.hypothes.is/https://foo.sni.velox.ch/

**Comment by ikreymer** [comment]
Tested some more locally with these sites and `ndg-httpsclient`, I think that should hopefully fix the SNI issues.

**Comment by ikreymer** [comment]
Fixed now
